const CONFIG = {
    titleWeb: "Muahahahaha",
    introTitle: 'Hẽ lou pạn',
    introDesc: `Bây giờ chơi 1 trò chơi với mình khôm?? UwU`,
    btnIntro: 'OKEY NUÔN NHA!!',
    title: 'CỨ TRẢ LỜI MỤT CÁCH TỰ NHIÊN NHA :33',
    desc: 'Pạn có thấy mình mập không???',
    btnYes: 'Khôm nhaa <33',
    btnNo: 'có gất nhiều :DD',
    question: 'Sao lại nghĩ dzậy dọ?? ><',
    btnReply: 'Gửi cho pạn nà <3',
    reply: 'Hí hí tại pạn cute thấy mồ <3333333',
    mess: 'mình pít mà!!! Yêu pạn nhieeufuuuuuu >< Muahahaahahha UwU',
    messDesc: 'Còn gì mà khôm đi nhắn cho tuôi liền :33',
    btnAccept: 'Okey nuôn nhaaa <3',
    messLink: 'https://github.com/zukahai/Confess-Crush'
